// Maps each stats API "Event Source" label to the source site's display_url,
// from https://github.com/alexroginski1/stuff_to_do/blob/main/config/settings.py's
// SOURCES dict — synced by hand, so a newly added upstream source won't show a
// link here until this map is updated too. "Manually Added Events" has no entry
// on purpose: it's the calendar owner's own curated additions, not a scraped site.
export const EVENT_SOURCE_LINKS: Record<string, string> = {
  "The Faight": "https://www.thefaight.com/events",
  "Decentered Featured Events": "https://decentered.org/events",
  "SF Funcheap": "https://sf.funcheap.com/region/san-francisco/",
  "Luma": "https://luma.com/sf",
  "Decentered Community Events": "https://decentered.org/events",
  "Manny's: Community, Politics, and Culture": "https://www.eventbrite.com/o/mannys-community-politics-and-culture-15114280512",
  "The SF Nook: SF Event Space": "https://www.thesfnook.com/events",
  "The Commons: Third Space": "https://luma.com/thecommons",
  "Future of Us": "https://luma.com/future-of-us",
  "The SF Contemplarium": "https://luma.com/sfcontemplarium",
  "TIAT Art and Tech": "https://luma.com/tiat",
  "Partiful": "https://partiful.com/explore/sf",
  "Mox Event Space": "https://moxsf.com/events",
  "Art Bae": "https://www.artbae.info/map-calendar",
  "SF Art Galleries - Openings & Events": "https://calendar.google.com/calendar/embed?src=33alanb%40gmail.com&ctz=America%2FLos_Angeles",
  "SF Bar Guide": "https://www.sfbarguide.com/",
  "Golden Sardine": "https://www.goldensardinesf.com/events",
  "The Saloon": "https://ma.to/venue/thesaloonsf",
  "The Makeout Room": "http://www.makeoutroom.com/",
  "Root Division": "https://rootdivision.org/gallery/events/",
  "ARCH Art Supplies: Workshops & Events": "https://shop.archsupplies.com/pages/workshops",
  "Flax: Art & Design": "https://flaxart.com/workshops-events/?srsltid=AfmBOooYfLsyvCosDkqgH2sP92_eUxOztus_wk68Wy-RaVG6U1l6S3zv",
  "Madrone Art Bar": "https://www.eventbrite.com/o/madrone-art-bar-33448786911",
  "Balboa Cafe": "https://www.balboacafesf.com/calendar",
  "SF Climate Action Club": "https://luma.com/climateactionclub",
  "SF Craft Club": "https://luma.com/user/sfcraftclub",
  "GistIRL: Make Friends and Network": "https://app.gistirl.com/",
  "Unplug and Play Collective": "https://www.unplugandplaycollective.com/",
  "Moonlit Moves: Mission 22nd St": "https://calendar.google.com/calendar/embed?src=f3bfcf5b10ff8cb2ba35abba749ccd68bc8347e2d522e6baca32448c9b2695cc%40group.calendar.google.com&ctz=America%2FLos_Angeles",
  "Community Music Hangout": "https://calendar.google.com/calendar/embed?src=88c5018286c9ab2d0e27326287e61a2b5d42b3ed4008ba650b81f054f65026dd%40group.calendar.google.com&ctz=America%2FLos_Angeles",
  "Fat Boys Run Club": "https://www.heylo.com/g/75ea182e-9df2-4b4d-bc78-a2e299384993",
  "Midnight Runners SF": "https://www.heylo.com/g/-LmBjhGfivWBeac11cNQ",
  "November Project SF": "https://www.heylo.com/g/48f5e552-13d3-4987-bd0b-66e8855dfd46",
  "Page Street Fit": "https://www.heylo.com/g/6e3b8574-b970-4713-995a-1c641daeca26",
  "SF Pickup Volleyball": "https://www.heylo.com/g/-LsD1YBcDKPOcrsMQ-mT",
  "San Francisco Beach Volleyball - SFBV": "https://www.heylo.com/g/7b9b7d08-d381-4280-bbc7-612795d40302",
  "Nob Hill Run Club": "https://partiful.com/u/gaH33LxCrvQo0r1F2Y5M",
  "GatherSF": "https://partiful.com/u/HoM5CgWY4UxtI5vu9HtU",
  "Studio 203: Figure Drawing": "https://www.meetup.com/studio-203-figure-drawing/",
  "San Francisco Chess Club": "https://partiful.com/u/98UJpsxnnCr8p7cb77hD",
  "Touch Grass Walk Club": "https://partiful.com/u/3Kd8VzusjiFIN0wx4TVs",
  "Board Games with EGL": "https://www.heylo.com/g/12979145-cf38-42c9-b755-e3a27b458bf9",
  "The Web SF": "https://www.heylo.com/g/1fda3590-3f27-4ee0-afc1-a63473b8a200",
  "Lower Haight Local": "https://www.heylo.com/g/18608def-640e-4bb9-8331-1d28f1908040",
  "Sapiens": "https://www.heylo.com/g/b30541ef-38c1-40c6-af55-3d100bf5d93d",
  "Bad Art Club": "https://www.eventbrite.com/cc/bad-art-club-4684923",
  "Founders Running Club San Francisco": "https://www.heylo.com/g/1270104d-2bf6-4f8c-ae29-22ef502df080",
  "The San Francisco 'Not Quite a Book Club' Book Club": "https://www.meetup.com/the-san-francisco-not-quite-a-book-club-book-club/",
  "SF Social Mixers and Networking": "https://www.meetup.com/sf-social-mixers-and-networking/",
  "20 & 30-somethings friends & fun in SF": "https://www.meetup.com/20-somethings-friends-fun-in-sf/",
  "San Francisco Philosophy Reading Group": "https://www.meetup.com/sf-philosophy-reading-group/",
  "Music Jam SF": "https://www.meetup.com/meetup-group-dvhbxtfg/",
  "Global AI Makers \u2022 West Coast": "https://www.meetup.com/global-ai-makers-san-francisco/",
  "San Francisco Startup Pitch and Networking": "https://www.meetup.com/sanfrancisco-startup-pitch-and-networking/",
  "Bay Area Socials": "https://www.meetup.com/baysocials/",
  "Play Games Learn Names": "https://www.meetup.com/san-francisco-game-meetup-group/",
  "San Francisco Movie Club": "https://www.meetup.com/sf-movie-club/",
  "San Francisco AI Code and Coffee": "https://www.meetup.com/sf-code-coffee/",
  "San Francisco Vegan Society Events": "https://www.meetup.com/sfvegansociety/",
  "SF Mission Fun Runs": "https://www.meetup.com/missionfunruns/",
  "San Francisco Bay Area Blood on the Clocktower": "https://www.meetup.com/san-francisco-blood-on-the-clocktower/",
  "San Francisco Artsy Stuff": "https://www.meetup.com/meetup-group-glpdmivm/",
  "Free Yoga SF": "https://www.meetup.com/fitnesssf/",
  "Bay Area Social Scene": "https://www.meetup.com/bay-area-social-scene/",
  "San Francisco Photographers": "https://www.meetup.com/sf-photo/",
  "SF Sketchers": "https://www.meetup.com/sf-sketchers/",
  "SF Zen Center": "https://www.sfzc.org/city-center-calendar",
  "Fort Mason Center for Arts & Culture": "https://www.eventbrite.com/o/20246696685",
  "A Listers Entertainment": "https://www.eventbrite.com/o/12913251409",
  "Fog City Run": "https://www.heylo.com/g/eba0b87a-f4ca-4ff2-bdfb-0d6b4729eb84",
  "Presidio Events": "https://presidio.gov/explore/events",
  "Dance Fridays": "https://www.eventbrite.com/o/dance-fridays-8106527232",
  "SFMOMA": "https://www.sfmoma.org/events/",
  "BATS Improv": "https://www.eventbrite.com/o/bats-improv-shows-120768857464",
}
