name = "alexroginski-website"
pages_build_output_dir = "out"

[vars]
NOMINATIM_CONTACT_EMAIL = "roginskialexr@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "stuff-to-do-survey"
database_id = "474ebaef-ea04-4093-a44e-a71d3a09ac6a"
